/*
    Copyright 2017-2022 Charles Korn.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

package batect.dockerclient.buildtools.codegen

import org.gradle.api.Task

internal val Task.licenseText: String
    get() = this.project.rootDir.resolve("gradle").resolve("license.txt").readText(Charsets.UTF_8).trim()

internal val Task.kotlinFileHeader: String
    get() =
        "/*\n" +
            licenseText.lines().joinToString("\n") { "    $it".trimEnd() } +
            """
            |
            |*/
            |
            |// AUTOGENERATED
            |// This file is autogenerated by the ${this.path} Gradle task.
            |// Do not edit this file, as it will be regenerated automatically next time this project is built.
            |
            """.trimMargin()
