/*
    Copyright 2017-2021 Charles Korn.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

package batect.dockerclient.buildtools.codegen

import com.charleskorn.kaml.PolymorphismStyle
import com.charleskorn.kaml.Yaml
import com.charleskorn.kaml.YamlConfiguration
import kotlinx.serialization.builtins.ListSerializer
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.nio.file.Files

abstract class GenerateGolangTypes : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val sourceFile: RegularFileProperty

    @get:OutputFile
    abstract val headerFile: RegularFileProperty

    init {
        group = "code generation"

        sourceFile.convention(
            project.provider {
                project.rootProject.layout.projectDirectory.file("codegen/types.yml")
            }
        )

        headerFile.convention(
            project.provider {
                project.layout.projectDirectory.file("src/types.h")
            }
        )
    }

    @TaskAction
    fun run() {
        val configuration = loadConfiguration()
        generateHeaderFile(configuration)
    }

    private fun generateHeaderFile(configuration: Map<String, Type>) {
        val builder = StringBuilder()

        builder.appendLine(
            """
            // Copyright 2017-2021 Charles Korn.
            //
            // Licensed under the Apache License, Version 2.0 (the "License");
            // you may not use this file except in compliance with the License.
            // You may obtain a copy of the License at
            //
            //     http://www.apache.org/licenses/LICENSE-2.0
            //
            // Unless required by applicable law or agreed to in writing, software
            // distributed under the License is distributed on an "AS IS" BASIS,
            // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
            // See the License for the specific language governing permissions and
            // limitations under the License.

            // This file is autogenerated by the ${this.path} Gradle task.
            // Do not edit this file, as it will be regenerated automatically next time this project is built.

            #include <stdint.h>
            #include <stdbool.h>

            #ifndef TYPES_H
            #define TYPES_H

            #ifdef WINDOWS
            #define EXPORTED_FUNCTION extern __declspec(dllexport)
            #else
            #define EXPORTED_FUNCTION
            #endif

            """.trimIndent()
        )

        configuration.values.forEach { type ->
            generateHeaderFileContentForType(builder, type, configuration)
        }

        builder.appendLine(
            """
            #endif
            """.trimIndent()
        )

        Files.writeString(headerFile.get().asFile.toPath(), builder, Charsets.UTF_8)
    }

    private fun generateHeaderFileContentForType(builder: StringBuilder, type: Type, configuration: Map<String, Type>) {
        when (type) {
            is AliasType -> {
                builder.appendLine("typedef ${type.nativeType} ${type.name};")
                builder.appendLine()
            }
            is StructType -> {
                builder.appendLine("typedef struct {")

                type.fields.forEach { (fieldName, fieldType) ->
                    builder.appendLine(generateHeaderFileContentForStructField(type, fieldName, fieldType, configuration))
                }

                builder.appendLine("} ${type.name};")
                builder.appendLine()
                builder.appendLine("EXPORTED_FUNCTION ${type.name}* Alloc${type.name}();")
                builder.appendLine("EXPORTED_FUNCTION void Free${type.name}(${type.name}* value);")
                builder.appendLine()
            }
        }
    }

    private fun generateHeaderFileContentForStructField(parentType: StructType, fieldName: String, fieldType: String, configuration: Map<String, Type>): String {
        val resolvedType = resolveTypeReference(fieldType, configuration, "for field '$fieldName' in struct '${parentType.name}'")

        return "    ${resolvedType.cName} $fieldName;"
    }

    private fun resolveTypeReference(typeName: String, configuration: Map<String, Type>, errorContext: String): TypeInformation {
        if (configuration.containsKey(typeName)) {
            return configuration[typeName]!!
        }

        if (PrimitiveType.yamlNamesToValues.containsKey(typeName)) {
            return PrimitiveType.yamlNamesToValues[typeName]!!
        }

        throw IllegalArgumentException("Unknown type '$typeName' $errorContext.")
    }

    private fun loadConfiguration(): Map<String, Type> {
        val path = sourceFile.get()
        val content = Files.readString(path.asFile.toPath())
        val yaml = Yaml(configuration = YamlConfiguration(polymorphismStyle = PolymorphismStyle.Property))

        val types = yaml.decodeFromString(ListSerializer(Type.serializer()), content)

        return types.associateBy { it.yamlName }
    }
}
