/*
    Copyright 2017-2021 Charles Korn.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

// AUTOGENERATED
// This file is autogenerated by the :client:generateJvmMethods Gradle task.
// Do not edit this file, as it will be regenerated automatically next time this project is built.

package batect.dockerclient.native

import jnr.ffi.Pointer
import jnr.ffi.annotations.In

@Suppress("FunctionName")
internal interface API {
    fun CreateClient(): CreateClientReturn?
    fun DisposeClient(@In clientHandle: Long)
    fun Ping(@In clientHandle: Long): PingReturn?
    fun GetDaemonVersionInformation(@In clientHandle: Long): GetDaemonVersionInformationReturn?
    fun PullImage(@In clientHandle: Long, @In ref: String, @In onProgressUpdate: PullImageProgressCallback, @In callbackUserData: Pointer?): PullImageReturn?
    fun DeleteImage(@In clientHandle: Long, @In ref: String): Error?
    fun GetImage(@In clientHandle: Long, @In ref: String): GetImageReturn?
    fun CreateNetwork(@In clientHandle: Long, @In name: String, @In driver: String): CreateNetworkReturn?
    fun DeleteNetwork(@In clientHandle: Long, @In id: String): Error?
    fun GetNetworkByNameOrID(@In clientHandle: Long, @In searchFor: String): GetNetworkByNameOrIDReturn?
    fun CreateVolume(@In clientHandle: Long, @In name: String): CreateVolumeReturn?
    fun DeleteVolume(@In clientHandle: Long, @In name: String): Error?
    fun ListAllVolumes(@In clientHandle: Long): ListAllVolumesReturn?
    fun FreeError(@In value: Error)
    fun AllocError(): Error?
    fun FreeCreateClientReturn(@In value: CreateClientReturn)
    fun AllocCreateClientReturn(): CreateClientReturn?
    fun FreePingResponse(@In value: PingResponse)
    fun AllocPingResponse(): PingResponse?
    fun FreePingReturn(@In value: PingReturn)
    fun AllocPingReturn(): PingReturn?
    fun FreeDaemonVersionInformation(@In value: DaemonVersionInformation)
    fun AllocDaemonVersionInformation(): DaemonVersionInformation?
    fun FreeGetDaemonVersionInformationReturn(@In value: GetDaemonVersionInformationReturn)
    fun AllocGetDaemonVersionInformationReturn(): GetDaemonVersionInformationReturn?
    fun FreeVolumeReference(@In value: VolumeReference)
    fun AllocVolumeReference(): VolumeReference?
    fun FreeCreateVolumeReturn(@In value: CreateVolumeReturn)
    fun AllocCreateVolumeReturn(): CreateVolumeReturn?
    fun FreeListAllVolumesReturn(@In value: ListAllVolumesReturn)
    fun AllocListAllVolumesReturn(): ListAllVolumesReturn?
    fun FreeNetworkReference(@In value: NetworkReference)
    fun AllocNetworkReference(): NetworkReference?
    fun FreeCreateNetworkReturn(@In value: CreateNetworkReturn)
    fun AllocCreateNetworkReturn(): CreateNetworkReturn?
    fun FreeGetNetworkByNameOrIDReturn(@In value: GetNetworkByNameOrIDReturn)
    fun AllocGetNetworkByNameOrIDReturn(): GetNetworkByNameOrIDReturn?
    fun FreeImageReference(@In value: ImageReference)
    fun AllocImageReference(): ImageReference?
    fun FreePullImageReturn(@In value: PullImageReturn)
    fun AllocPullImageReturn(): PullImageReturn?
    fun FreePullImageProgressDetail(@In value: PullImageProgressDetail)
    fun AllocPullImageProgressDetail(): PullImageProgressDetail?
    fun FreePullImageProgressUpdate(@In value: PullImageProgressUpdate)
    fun AllocPullImageProgressUpdate(): PullImageProgressUpdate?
    fun FreeGetImageReturn(@In value: GetImageReturn)
    fun AllocGetImageReturn(): GetImageReturn?
}
