FROM alpine:3.18.0

RUN echo "Value of FTP_PROXY is $FTP_PROXY"
RUN echo "Value of ftp_proxy is $ftp_proxy"
RUN echo "Value of HTTPS_PROXY is $HTTPS_PROXY"
RUN echo "Value of https_proxy is $https_proxy"
RUN echo "Value of HTTP_PROXY is $HTTP_PROXY"
RUN echo "Value of http_proxy is $http_proxy"
RUN echo "Value of NO_PROXY is $NO_PROXY"
RUN echo "Value of no_proxy is $no_proxy"
