comments:
  active: true
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true

complexity:
  active: true
  LargeClass:
    active: false
  TooManyFunctions:
    active: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false

style:
  active: true
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: false
  MagicNumber:
    active: false
