# Recreate this image with 'resources/base-images/recreate.sh'.
FROM ghcr.io/batect/docker-client:legacy-image-build-pull-progress@sha256:a4b51dce3a4b2cc09a2d517c2239b763a84d28e9ab66ce051f2006262f454a24
