// Copyright 2017-2021 Charles Korn.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// AUTOGENERATED
// This file is autogenerated by the :golang-wrapper:generateTypes Gradle task.
// Do not edit this file, as it will be regenerated automatically next time this project is built.

#include <stdlib.h>
#include "types.h"

Error* AllocError() {
    Error* value = malloc(sizeof(Error));
    value->Type = NULL;
    value->Message = NULL;

    return value;
}

void FreeError(Error* value) {
    if (value == NULL) {
        return;
    }

    free(value->Type);
    free(value->Message);
    free(value);
}

TLSConfiguration* AllocTLSConfiguration() {
    TLSConfiguration* value = malloc(sizeof(TLSConfiguration));
    value->CAFilePath = NULL;
    value->CertFilePath = NULL;
    value->KeyFilePath = NULL;

    return value;
}

void FreeTLSConfiguration(TLSConfiguration* value) {
    if (value == NULL) {
        return;
    }

    free(value->CAFilePath);
    free(value->CertFilePath);
    free(value->KeyFilePath);
    free(value);
}

ClientConfiguration* AllocClientConfiguration() {
    ClientConfiguration* value = malloc(sizeof(ClientConfiguration));
    value->Host = NULL;
    value->TLS = NULL;
    value->ConfigDirectoryPath = NULL;

    return value;
}

void FreeClientConfiguration(ClientConfiguration* value) {
    if (value == NULL) {
        return;
    }

    free(value->Host);
    FreeTLSConfiguration(value->TLS);
    free(value->ConfigDirectoryPath);
    free(value);
}

CreateClientReturn* AllocCreateClientReturn() {
    CreateClientReturn* value = malloc(sizeof(CreateClientReturn));
    value->Error = NULL;

    return value;
}

void FreeCreateClientReturn(CreateClientReturn* value) {
    if (value == NULL) {
        return;
    }

    FreeError(value->Error);
    free(value);
}

PingResponse* AllocPingResponse() {
    PingResponse* value = malloc(sizeof(PingResponse));
    value->APIVersion = NULL;
    value->OSType = NULL;
    value->BuilderVersion = NULL;

    return value;
}

void FreePingResponse(PingResponse* value) {
    if (value == NULL) {
        return;
    }

    free(value->APIVersion);
    free(value->OSType);
    free(value->BuilderVersion);
    free(value);
}

PingReturn* AllocPingReturn() {
    PingReturn* value = malloc(sizeof(PingReturn));
    value->Response = NULL;
    value->Error = NULL;

    return value;
}

void FreePingReturn(PingReturn* value) {
    if (value == NULL) {
        return;
    }

    FreePingResponse(value->Response);
    FreeError(value->Error);
    free(value);
}

DaemonVersionInformation* AllocDaemonVersionInformation() {
    DaemonVersionInformation* value = malloc(sizeof(DaemonVersionInformation));
    value->Version = NULL;
    value->APIVersion = NULL;
    value->MinAPIVersion = NULL;
    value->GitCommit = NULL;
    value->OperatingSystem = NULL;
    value->Architecture = NULL;

    return value;
}

void FreeDaemonVersionInformation(DaemonVersionInformation* value) {
    if (value == NULL) {
        return;
    }

    free(value->Version);
    free(value->APIVersion);
    free(value->MinAPIVersion);
    free(value->GitCommit);
    free(value->OperatingSystem);
    free(value->Architecture);
    free(value);
}

GetDaemonVersionInformationReturn* AllocGetDaemonVersionInformationReturn() {
    GetDaemonVersionInformationReturn* value = malloc(sizeof(GetDaemonVersionInformationReturn));
    value->Response = NULL;
    value->Error = NULL;

    return value;
}

void FreeGetDaemonVersionInformationReturn(GetDaemonVersionInformationReturn* value) {
    if (value == NULL) {
        return;
    }

    FreeDaemonVersionInformation(value->Response);
    FreeError(value->Error);
    free(value);
}

VolumeReference* AllocVolumeReference() {
    VolumeReference* value = malloc(sizeof(VolumeReference));
    value->Name = NULL;

    return value;
}

void FreeVolumeReference(VolumeReference* value) {
    if (value == NULL) {
        return;
    }

    free(value->Name);
    free(value);
}

CreateVolumeReturn* AllocCreateVolumeReturn() {
    CreateVolumeReturn* value = malloc(sizeof(CreateVolumeReturn));
    value->Response = NULL;
    value->Error = NULL;

    return value;
}

void FreeCreateVolumeReturn(CreateVolumeReturn* value) {
    if (value == NULL) {
        return;
    }

    FreeVolumeReference(value->Response);
    FreeError(value->Error);
    free(value);
}

ListAllVolumesReturn* AllocListAllVolumesReturn() {
    ListAllVolumesReturn* value = malloc(sizeof(ListAllVolumesReturn));
    value->Volumes = NULL;
    value->Error = NULL;
    value->VolumesCount = 0;

    return value;
}

void FreeListAllVolumesReturn(ListAllVolumesReturn* value) {
    if (value == NULL) {
        return;
    }

    for (uint64_t i = 0; i < value->VolumesCount; i++) {
        FreeVolumeReference(value->Volumes[i]);
    }

    free(value->Volumes);
    FreeError(value->Error);
    free(value);
}

NetworkReference* AllocNetworkReference() {
    NetworkReference* value = malloc(sizeof(NetworkReference));
    value->ID = NULL;

    return value;
}

void FreeNetworkReference(NetworkReference* value) {
    if (value == NULL) {
        return;
    }

    free(value->ID);
    free(value);
}

CreateNetworkReturn* AllocCreateNetworkReturn() {
    CreateNetworkReturn* value = malloc(sizeof(CreateNetworkReturn));
    value->Response = NULL;
    value->Error = NULL;

    return value;
}

void FreeCreateNetworkReturn(CreateNetworkReturn* value) {
    if (value == NULL) {
        return;
    }

    FreeNetworkReference(value->Response);
    FreeError(value->Error);
    free(value);
}

GetNetworkByNameOrIDReturn* AllocGetNetworkByNameOrIDReturn() {
    GetNetworkByNameOrIDReturn* value = malloc(sizeof(GetNetworkByNameOrIDReturn));
    value->Response = NULL;
    value->Error = NULL;

    return value;
}

void FreeGetNetworkByNameOrIDReturn(GetNetworkByNameOrIDReturn* value) {
    if (value == NULL) {
        return;
    }

    FreeNetworkReference(value->Response);
    FreeError(value->Error);
    free(value);
}

ImageReference* AllocImageReference() {
    ImageReference* value = malloc(sizeof(ImageReference));
    value->ID = NULL;

    return value;
}

void FreeImageReference(ImageReference* value) {
    if (value == NULL) {
        return;
    }

    free(value->ID);
    free(value);
}

PullImageReturn* AllocPullImageReturn() {
    PullImageReturn* value = malloc(sizeof(PullImageReturn));
    value->Response = NULL;
    value->Error = NULL;

    return value;
}

void FreePullImageReturn(PullImageReturn* value) {
    if (value == NULL) {
        return;
    }

    FreeImageReference(value->Response);
    FreeError(value->Error);
    free(value);
}

PullImageProgressDetail* AllocPullImageProgressDetail() {
    PullImageProgressDetail* value = malloc(sizeof(PullImageProgressDetail));

    return value;
}

void FreePullImageProgressDetail(PullImageProgressDetail* value) {
    if (value == NULL) {
        return;
    }

    free(value);
}

PullImageProgressUpdate* AllocPullImageProgressUpdate() {
    PullImageProgressUpdate* value = malloc(sizeof(PullImageProgressUpdate));
    value->Message = NULL;
    value->Detail = NULL;
    value->ID = NULL;

    return value;
}

void FreePullImageProgressUpdate(PullImageProgressUpdate* value) {
    if (value == NULL) {
        return;
    }

    free(value->Message);
    FreePullImageProgressDetail(value->Detail);
    free(value->ID);
    free(value);
}

bool InvokePullImageProgressCallback(PullImageProgressCallback method, void* userData, PullImageProgressUpdate* progress) {
    return method(userData, progress);
}

GetImageReturn* AllocGetImageReturn() {
    GetImageReturn* value = malloc(sizeof(GetImageReturn));
    value->Response = NULL;
    value->Error = NULL;

    return value;
}

void FreeGetImageReturn(GetImageReturn* value) {
    if (value == NULL) {
        return;
    }

    FreeImageReference(value->Response);
    FreeError(value->Error);
    free(value);
}

VolumeReference** CreateVolumeReferenceArray(uint64_t size) {
    return malloc(size * sizeof(VolumeReference*));
}

void SetVolumeReferenceArrayElement(VolumeReference** array, uint64_t index, VolumeReference* value) {
    array[index] = value;
}
