// Copyright 2017-2021 Charles Korn.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// AUTOGENERATED
// This file is autogenerated by the :docker-client-wrapper:generateTypes Gradle task.
// Do not edit this file, as it will be regenerated automatically next time this project is built.

package main

/*
    #cgo windows CFLAGS: -DWINDOWS=1
    #include "types.h"
*/
import "C"

type DockerClient C.DockerClient
type PingResponse *C.PingResponse
type Error *C.Error
type PingReturn *C.PingReturn
type CreateClientReturn *C.CreateClientReturn

func newPingResponse(
    APIVersion string,
    OSType string,
    Experimental bool,
    BuilderVersion string,
) PingResponse {
    value := C.AllocPingResponse()
    value.APIVersion = C.CString(APIVersion)
    value.OSType = C.CString(OSType)
    value.Experimental = C.bool(Experimental)
    value.BuilderVersion = C.CString(BuilderVersion)

    return value
}

func newError(
    Type string,
    Message string,
) Error {
    value := C.AllocError()
    value.Type = C.CString(Type)
    value.Message = C.CString(Message)

    return value
}

func newPingReturn(
    Response PingResponse,
    Error Error,
) PingReturn {
    value := C.AllocPingReturn()
    value.Response = Response
    value.Error = Error

    return value
}

func newCreateClientReturn(
    Client DockerClient,
    Error Error,
) CreateClientReturn {
    value := C.AllocCreateClientReturn()
    value.Client = C.uint64_t(Client)
    value.Error = Error

    return value
}

